#!/bin/sh
"""": # -*-python-*-
bup_python="$(dirname "$0")/../cmd/bup-python" || exit $?
exec "$bup_python" "$0" ${1+"$@"}
"""
# end of bup preamble

from sys import stderr
import sys, platform


if platform.system().startswith('CYGWIN'):
    # As of Cygwin x86_64's python 2.7.10-1 package, ctypes.cdll.shell32.IsUserAndAdmin is not defined.
    print >> stderr, "can't detect root status on Cygwin; assuming not root"
    print 'none'
elif platform.system().startswith('Windows'):
    if sys.getwindowsversion()[0] > 5:
        # Sounds like situation is much more complicated here
        print >> stderr, "can't detect root status for OS version > 5; assuming not root"
        print 'none'
    else:
        import ctypes
        if ctypes.cdll.shell32.IsUserAnAdmin():
            print 'root'
        else:
            print 'none'
else:
    import os
    if os.environ.get('FAKEROOTKEY'):
        print 'fake'
    else:
        if os.geteuid() == 0:
            print 'root'
        else:
            print 'none'
